### ISSUE TITLE
output is not json format

### ISSUE THREAD

**Issue by hennande** [siznax/wptools#1]
Thanks for the release,

But when I run "./infobox.py University_of_Cambridge", the output contains 631 lines and is not in json format. Does this problem occurs on your computer?

**Comment by siznax** [comment]
This problem resulted from not checking if the value found from the template part was None before trying to get the text. In `University_of_Cambridge`, the "website" part of the infobox template contains another template (but no bare text) as its first value, so lxml returned NoneType.

```python
>>> type(etree.fromstring("<part><name>website </name>=<value><template><title>url</title><part><name index=\"1\"/><value>cam.ac.uk/</value></part></template>\n</value></part>").find('value').text)

<type 'NoneType'>
```

Commit a1ec305bcf7db51e6b757ebe5299cdf50ec717de improved error-handling:

```json
    "wptools.extract ERROR": "<part><name>website </name>=<value><template><title>url</title><part><name index=\"1\"/><value>cam.ac.uk/</value></part></template>\n</value></part>",
```

Commit e077cc93d3eb0db58a02693396d954e4563021d1 looks for a template value first:

```json
    "website": "<template><title>url</title><part><name index=\"1\"/><value>cam.ac.uk/</value></part></template>",
```

thus, resolving this issue.

**Comment by hennande** [comment]
Thanks for the solution
