### ISSUE TITLE
Add image license info

### ISSUE THREAD

**Issue by matkoniecz** [siznax/wptools#104]
to use image correctly one needs to know about its license - for example what, if any, attribution is required

from looking at https://github.com/siznax/wptools/wiki/Images this library has no function with such functionality

**Comment by siznax** [comment]
Hi @matkoniecz. Mediawiki [API:Imageinfo](https://www.mediawiki.org/wiki/API:Imageinfo) does not offer license information. It is the user's responsibility to make proper use of API data as described in [API: Licensing](https://www.mediawiki.org/wiki/API:Licensing).

**Comment by siznax** [comment]
As mentioned in #105, it turns out that **API:Imageinfo** does offer image license info with `iiprop=extmetadata`:

File:Gull portrait ca usa.jpg: https://commons.wikimedia.org/w/api.php?action=query&titles=File:Gull%20portrait%20ca%20usa.jpg&prop=imageinfo&iiprop=metadata|commonmetadata|extmetadata

```json
"extmetadata": {
    "Credit": {
        "value": "Self-published work by <a href=\"//commons.wikimedia.org/wiki/User:Dschwen\" title=\"User:Dschwen\">Dschwen</a>",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "Artist": {
        "value": "<a href=\"//commons.wikimedia.org/wiki/User:Dschwen\" title=\"User:Dschwen\">Dschwen</a>",
        "source": "commons-desc-page"
    },
    "LicenseShortName": {
        "value": "CC BY 2.5",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "UsageTerms": {
        "value": "Creative Commons Attribution 2.5",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "AttributionRequired": {
        "value": "true",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "LicenseUrl": {
        "value": "http://creativecommons.org/licenses/by/2.5",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "Copyrighted": {
        "value": "True",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "Restrictions": {
        "value": "",
        "source": "commons-desc-page",
        "hidden": ""
    },
    "License": {
        "value": "cc-by-2.5",
        "source": "commons-templates",
        "hidden": ""
    }
```

So, we'll put all of this info, verbatim, into a new `metadata` attribute for each image.

**Comment by seansay** [comment]
@siznax 
thanks! This is really useful!

**Comment by siznax** [comment]
Note: this image metadata is called `extmetadata` because it comes from [Extension:CommonsMetadata](https://www.mediawiki.org/wiki/Extension:CommonsMetadata) which appears to be stable.

**Comment by siznax** [comment]
Including this in the next release. Thanks so much for opening this issue @matkoniecz!

**Comment by matkoniecz** [comment]
And thanks for implementing it!

**Comment by siznax** [comment]
No problem. We use Milestones to indicate what we're working on for the next release (see [Release v0.4.8](https://github.com/siznax/wptools/milestone/3?closed=1) milestone). That release is now available on [pypi](https://pypi.python.org/pypi/wptools/).
