### ISSUE TITLE
Add image quality Assessment

### ISSUE THREAD

**Issue by matkoniecz** [siznax/wptools#105]
it may desirable to have ability to check whatever image is https://commons.wikimedia.org/wiki/Commons:Quality_images or https://commons.wikimedia.org/wiki/Commons:Featured_pictures

For example in my case I want to select single image from multiple articles, so it is preferable to select one marked as high-quality rather than random one

**Comment by siznax** [comment]
Thanks for opening an issue @matkoniecz!

It looks like [API:Imageinfo](https://www.mediawiki.org/wiki/API:Imageinfo) offers Assessment info with `iiprop=extmetadata`:

https://commons.wikimedia.org/w/api.php?action=query&titles=File:Gull%20portrait%20ca%20usa.jpg&prop=imageinfo&iiprop=metadata|commonmetadata|extmetadata

```json
"extmetadata": {
    "Assessments": {
        "value": "featured|poty|potd|quality",
        "source": "commons-categories",
        "hidden": ""
    },
```

So, I propose we put this information verbatim in a new 'metadata' attribute for each image which will be populated with the `get_imageinfo()` request. 

Image attribution and usage info are also in this property, so I'll re-open #104 to address it with the same approach.

**Comment by siznax** [comment]
Note: our image metadata is called `extmetadata` because it comes from [Extension:CommonsMetadata](https://www.mediawiki.org/wiki/Extension:CommonsMetadata)

**Comment by siznax** [comment]
See also [Commons:Assessments](https://commons.wikimedia.org/wiki/Commons:Assessments).
