### ISSUE TITLE
Support for languages other than english

### ISSUE THREAD

**Issue by boompig** [siznax/wptools#113]
I believe that `en.wikipedia.org` is hard-coded everywhere as the base URL for queries. Can this be replaced with a parameter (that defaults to `en.wikipedia.org`) so there can be support for other languages, for example `nl.wikipedia.org`?

**Comment by siznax** [comment]
Thanks for trying wptools, @boompig. Supporting as many languages as possible is a core tenet of this package. As mentioned in the [wiki](https://github.com/siznax/wptools/wiki), you can use either the `lang`, or the `wiki` parameter:

```python
>>> page = wptools.page(lang='nl')
nl.wikipedia.org (random) 🍩
Gastromyzon psiloetron (nl) data
{
  pageid: 3070356
  requests: <list(1)> random
  title: Gastromyzon psiloetron
}
```

```python
>>> page = wptools.page(wiki='nl.wikipedia.org')
nl.wikipedia.org (random) 🌯
Baetis celcus (en) data
{
  pageid: 3191637
  requests: <list(1)> random
  title: Baetis celcus
}
```

Let us know if you think we can improve the docs somehow.
