### ISSUE TITLE
Percent-encoded title causes API Error

### ISSUE THREAD

**Issue by dimoes** [siznax/wptools#117]
The following error is thrown when attempt to fetch title with odd character. Works works fine calling Wikimedia api directly.

Title=H%C3%B4tel_particulier

Error: API error: {u'info': u'Bad title "H%C3%B4tel_particulier".', u'code': u'invalidtitle', u'docref': u'See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}
UNEXPECTED ERROR

Note: I encode to UTF-8 NFC before passing along.

**Comment by siznax** [comment]
Thanks for trying wptools, @dimoes!

The WMF APIs need URL-encoded titles because they work directly over HTTP, but wptools wants a human-readable title. You can use `urllib.unquote()` to unquote your titles like this:

```python
>>> import wptools, urllib
>>> page = wptools.page(urllib.unquote('H%C3%B4tel_particulier'))
```
