### ISSUE TITLE
get Backlinks from page?

### ISSUE THREAD

**Issue by ferchaure** [siznax/wptools#119]
It would be useful to obtain the backlinks from a page. Is it possible?

https://www.mediawiki.org/wiki/API:Backlinks

**Comment by siznax** [comment]
Thanks for trying wptools and opening this issue @ferchaure! I've committed the initial update to support getting backlinks. We'll need to add support for continuations (`blcontinue` in the response) to complete this feature. It should work the same way as `cmcontinue` for categories. I should be able to get to that in the next few days. You're welcome to submit a pull request if you get to it first.

**Comment by siznax** [comment]
Need to add `data['backlinks']` to the wiki ([Data captured](https://github.com/siznax/wptools/wiki/Data-captured)). Also, I added more general "continue" methods to `wptools.core` for this feature, so we should make use of them in `wptools.category` to bring it into harmony.

**Comment by siznax** [comment]
This is now available in v0.4.13. Thanks again for opening an issue, @ferchaure!
