### ISSUE TITLE
Monkeypatch for python3  unicode

### ISSUE THREAD

**Issue by commutecat** [siznax/wptools#13]
For those who want to use wptools in python 3 after you clone the wptools and install local copy in your system. 

core.py 

```
-            if type(prop) is str or type(prop) is unicode:
+            if type(prop) is str:

```
Since python 3 move to str, it is difficult to make a patch that works for both python 2 and 3 for this particular unicode check. 

Version check is kinda tricky. 
```
import sys

if sys.version_info.major == "2":
   if type(prop) is str or type(prop) is unicode:
       .....
elif sys.version_info.major == "3":
   if type(prop) is str:
       .....
```

**Comment by siznax** [comment]
Thanks @commutecat! I'll see if I can use this to get wptools working in both python 2 and 3.
