### ISSUE TITLE
Parsed infobox data contains operator in right-hand-side

### ISSUE THREAD

**Issue by Voidi** [siznax/wptools#132]
I'm like to use wptools to extract the content of infoboxes from the MediWiki instance at [de.wiki-aventurica.de](https://de.wiki-aventurica.de). Testing with the english wikipedia produces results as expected.

After parsing - for example [de.wiki-aventurica.de/wiki/Benutzer:Voidi/Sandkasten](https://de.wiki-aventurica.de/wiki/Benutzer:Voidi/Sandkasten) - the infobox dict has values that are wrongly prefixed with '= '.

My Instructions:

```python
>>> page = wptools.page('Benutzer:Voidi/Sandkasten', endpoint='/de/api.php', wiki='de.wiki-aventurica.de')

>>> page.get_parse()

>>> page.data['infobox']
{'Name': '= gg', 'Bild': '= g', 'Art': '= g', 'Klasse': '= f', 'Beinamen': '= f', 'Domäne': '= Test2', 'Lehrmeister': '= d', 'Niederschrift': '= d'}
```

Has this something to do, how wptools parses wikitext or is something wrong with this wiki instance?

**Comment by Voidi** [comment]
The Wikitext as shown in the Web editor:
`{{Infobox Dämon
| Name = gg
| Bild = g
| Art = g
| Klasse = f
| Beinamen = f
| Domäne = Test2
| Lehrmeister = d
| Niederschrift = d
}}`

**Comment by siznax** [comment]
Thanks for trying wptools @Voidi! The wiki is probably fine. You can access the raw wikitext like so:
https://de.wiki-aventurica.de/wiki/Benutzer:Voidi/Sandkasten?action=raw

I'll look more closely at how we are parsing this particular wikitext. Thanks for the simple example!

**Comment by Voidi** [comment]
I compared the XML parse tree from the example in my wiki instance and a site from wikipedia:

1. 
[Ghandi](https://en.wikipedia.org//w/api.php?action=parse&format=json&formatversion=2&contentmodel=text&disableeditsection=&disablelimitreport=&disabletoc=&prop=text|iwlinks|parsetree|wikitext|displaytitle|properties&redirects&page=Ghandi)

`<part><name> name </name><equals>=</equals><value> Mohandas Karamchand Gandhi</value>`

2.
[Benutzer:Voidi/Sandkasten](https://de.wiki-aventurica.de/de/api.php?action=parse&format=json&formatversion=2&contentmodel=text&disableeditsection=&disablelimitreport=&disabletoc=&prop=text|iwlinks|parsetree|wikitext|displaytitle|properties&redirects&page=Benutzer:Voidi/Sandkasten)

`<part><name> Name </name>=<value> gg\n</value></part>`

What does this `<equal>` tag?

**Comment by Voidi** [comment]
`de.wiki-aventurica.de` has Mediawiki Version 1.30.0 and the english wikipedia has Version 1.32.0.

**Comment by siznax** [comment]
Like I said, @Voidi, in general Infobox data may require some cleanup because the data source is unstructured. Take a look at `wptools.utils.template_to_dict` and let us know if you think we can make any improvements.

**Comment by siznax** [comment]
Closing for now. Please re-open if you have more related questions @Voidi.
