### ISSUE TITLE
wptools installs files to weird places

### ISSUE THREAD

**Issue by antifa-ev** [siznax/wptools#135]
wptools installs files to weird places:

```
/usr/lib/python3.7/site-packages/scripts/__init__.py exists in filesystem (owned by python-wptools)
/usr/lib/python3.7/site-packages/scripts/__pycache__/__init__.cpython-37.opt-1.pyc exists in filesystem (owned by python-wptools)
/usr/lib/python3.7/site-packages/scripts/__pycache__/__init__.cpython-37.pyc exists in filesystem (owned by python-wptools)
```

I've installed it like I install most python packages since 10 years: `python setup.py install --optimize=1`

**Comment by siznax** [comment]
Thanks for trying wptools @antifa-ev!

Things have improved a bit in ten years. 😄 We recommend using a [virtualenv](https://virtualenvwrapper.readthedocs.io) to control where things end up on your system.

Please take a look at our `setup.py` and let us know if you think we can improve it.

**Comment by antifa-ev** [comment]
Actually I don't wont to use anything like virtualenv, conda or pypi.

**Comment by siznax** [comment]
Then, you may have to accept where your system puts files with `python setup.py install --optimize=1`

Is there something else you think we can do to help?

**Comment by siznax** [comment]
Feel free to re-open if you have any more ideas about this.
