### ISSUE TITLE
install wptools in anaconda env

### ISSUE THREAD

**Issue by wbagais** [siznax/wptools#137]
I want to install wptools in conda env to open it in jupyter notebook.

I tried "pip install wptool"  and then when I tried "conda list" it shows: 
wptools                   0.4.17                    <pip>

**however, when I "import wptools" below error msg appears:**
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-35-e610e0a711f9> in <module>
----> 1 import wptools

/anaconda3/envs/py3/lib/python3.7/site-packages/wptools/__init__.py in <module>
     21 __version__ = "0.4.17"
     22 
---> 23 from . import core
     24 from . import query
     25 from . import request

/anaconda3/envs/py3/lib/python3.7/site-packages/wptools/core.py in <module>
     12 from wptools.query import WPToolsQuery
     13 
---> 14 from . import request
     15 from . import utils
     16 

/anaconda3/envs/py3/lib/python3.7/site-packages/wptools/request.py in <module>
     15 
     16 import certifi
---> 17 import pycurl
     18 
     19 from . import __title__, __contact__, __version__

ImportError: dlopen(/anaconda3/envs/py3/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /anaconda3/envs/py3/lib/python3.7/site-packages/pycurl.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by siznax** [comment]
Thanks for trying wptools @wbagais! 

I'm not familiar with anaconda or jupyter notebooks, but it looks like your `anaconda3` virtual environment cannot load the `pycurl` library. You might want to search for non-specific parts of the error message.

When I search for "python conda ImportError Reason: image not found" I get some potentially useful results, like this one: https://stackoverflow.com/questions/50584217/launching-spyder-and-jupyternotebook-causese-importerror-when-image-not-found

Hope that helps.
