### ISSUE TITLE
mostviewed for en.wikipedia.org Returning Empty

### ISSUE THREAD

**Issue by wovendan** [siznax/wptools#146]
I've tried a lot of variations- seems like only the  en.wikipedia.org  site produces an empty list.  en.wikipedia.org is the default so I've tried with no params and etc...

site = wptools.site()
site.get_info('ja.wikipedia.org')
has expected results (a bunch of most viewed pages in data.mostviewed)
site = wptools.site()
site.get_info('en.wikipedia.org') 
does not, instead gives:
mostviewed: <list(0)>

Similarly:

site = wptools.site()
site.top('nl.wikipedia.org')
DOES work
site = wptools.site()
site.top('en.wikipedia.org')
does NOT work

**Comment by siznax** [comment]
Thanks for trying wptools @wovendan!

Weird. Looks like an issue with the [PageViewInfo](https://www.mediawiki.org/wiki/Extension:PageViewInfo) extension on `enwiki`:

https://en.wikipedia.org/w/api.php?action=query&list=mostviewed

```
{
    "batchcomplete": "",
    "query": {
        "mostviewed": []
    }
}
```

The bug has been reported: https://phabricator.wikimedia.org/T233381

I've asked there if there is an alternative. In the meantime, I'll look for another one.

**Comment by wovendan** [comment]
Ah thanks a million @siznax - its been driving me nuts but I would never have found that page on which I see you've added a comment and request for resolution! Your wrapper has helped me to have a go at integrating wikip stuff in a site I'm developing - if I can make the site pay for itself I'll buy you some beers- thanks very much for your efforts! Hugs. Dan    ps. in case the info is any use: mostviewed was working sporadically about a week ago and now seems to be completely dead; dunno what this signifies. D

**Comment by siznax** [comment]
Seems to be working again!
