### ISSUE TITLE
how to solve the traffic network issue? 

### ISSUE THREAD

**Issue by woshichuanqilz** [siznax/wptools#148]
When I use this package, I get a response like this 
 
Our systems have detected unusual traffic from your computer network.

 But  I can  access  wiki  Normally from my browser.  How to solve this problem? ?

![image](https://user-images.githubusercontent.com/11295355/74212121-a9dc1180-4ccd-11ea-8907-a30f95d51d46.png)

**Comment by siznax** [comment]
Thanks for trying wptools @woshichuanqilz 

The URL reported above is a google.com URL. I don't think it's coming from the MediaWiki API.

What happens when you click "Why did this happen?"
