### ISSUE TITLE
get_wikidata for arrays? 

### ISSUE THREAD

**Issue by aschimmenti** [siznax/wptools#166]
Hello, 
I'm really enjoying using wptools for scraping wikidata, is there a conditional to keep the e.g. for loop going even if an individual query gives Lookup Error? Thank you in advance

**Comment by aschimmenti** [comment]
Solved with try...except LookupError

**Comment by siznax** [comment]
Thank you @aschimmenti. That's the pythonic way to approach it. Nice work.
