### ISSUE TITLE
feature request: query page by pageid?

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#21]
Hi,

I'm wondering can I query a page by pageid? From docs seems not

**Comment by siznax** [comment]
Thanks for the question, @seansay. I added support for this (af7bbff74b10a154d69540812d1cc1b03c4cf437). It will work with `get_query` and `get_parse` directly, or via `get`:

```python
>>> import wptools
>>> p = wptools.page(pageid=851640).get()
en.wikipedia.org (action=query) 851640
en.wikipedia.org (action=parse) 851640
en.wikipedia.org (action=wikidata) Q26949
en.wikipedia.org (action=wikidata) Q16521|Q34740|Q8508070|Q666616
Helianthus (en)
{
  lang: en
  pageid: 851640
  title: Helianthus
  url: https://en.wikipedia.org/wiki/Helianthus
  wikibase: https://www.wikidata.org/wiki/Q26949
  ...
}
```

You can check that result against the _Helianthus_ page's "Page Information" link: https://en.wikipedia.org/w/index.php?title=Helianthus&action=info which shows:

```
Page ID	851640
```

Can you give me an example of what you want to do?

I'll publish a new revision if it works for you.

**Comment by seansay** [comment]
@siznax 

I have a list of musician's name, I want to get its short bio and things. But I also want to update it since the page content edit by someone else, so I kind of think when you updating, using the last pageid it's more accurate?

That's how I think.

Thanks for responding this so fast, appreciate it

**Comment by seansay** [comment]
Anyway, I still have the problem: how I can make sure the page I get (in the first time) is the person I want. That can be trikcy.

**Comment by seansay** [comment]
after some reading on the docs, maybe `wikibase id` is more suitable for my use case?

**Comment by siznax** [comment]
Yes, that can be tricky. I think using a `wikibase` ID is best if possible. However, if somehow you already have a list of `pageid` for them, then that could work now too.

Thanks again for the request!

**Comment by seansay** [comment]
@siznax 
I think I will using wikidata, because the claims is a nice way to distinguish whether is a band or person.  Thanks again!
