### ISSUE TITLE
feature request: proxy support

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#22]
sadly , from China. Many part of the wikipedia page is blocked,  if I can pass in a proxy that would be great

**Comment by seansay** [comment]
I saw the source code the request is made in curl, so basiclly some global config of proxy, and passing to curl if needed

**Comment by siznax** [comment]
Thanks for your request, @seansay. I added support for this (119ea6a00ef83366aa2b7d09000be6375592f243). Please let me know if it works for you.

**Comment by seansay** [comment]
thanks!

also, is that request is really slow than curl?

**Comment by siznax** [comment]
No problem! Yes. So far, I have not been able to get `requests` to perform as well as `pycurl` "out-of-the-box". I plan to look more closely at using `requests` before making a 1.0 release.
