### ISSUE TITLE
add api to set request timeout

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#28]
I'm using an proxy to reques wikipedia, so it reponse timeout often, could add a tiemout parameter is better?(like `requests` package)

```
  File "/var/dae/apps/fm/venv/src/wptools/wptools/fetch.py", line 112, in curl
    return self.curl_perform(crl)
  File "/var/dae/apps/fm/venv/src/wptools/wptools/fetch.py", line 120, in curl_perform
    crl.perform()
pycurl.error: (28, 'Operation timed out after 15000 milliseconds with 0 out of 0 bytes received')
```

**Comment by siznax** [comment]
Hi @seansay. Thanks for the request. I added the instance method `set_timeout()` (870b09098f77b76054e76f13cbd95d43acff988b). The timeout parameter is in seconds and covers the entire request (both connect and read). The default timeout ([curl TIMEOUT](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html)) is zero which means it will try to wait forever. 

```python
>>> help(wptools.page.set_timeout)
Help on method set_timeout in module wptools.core:

set_timeout(self, seconds) method of wptools.core.WPTools instance
    set timeout for entire request in seconds (default=0=forever)
```

Also, I wrapped `python.error` in `RuntimeError`:

```python
>>> a = wptools.page('a')
>>> a.set_timeout(1)
>>> a.get_parse()
en.wikipedia.org (action=parse) a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wptools/core.py", line 587, in get_parse
    parse['response'] = self.__fetch.curl(query)
  File "wptools/fetch.py", line 114, in curl
    raise RuntimeError("pycurl error %d %s" % (detail[0], detail[1]))
RuntimeError: pycurl error 28 Operation timed out after 1000 milliseconds with 0 bytes received
```

**Comment by seansay** [comment]
could you also add `proxy` and `timeout` to per query setting?

like `wptools.page("John Cage").get(timeout=5, proxy="")`, maybe this is more clean way to do it?

**Comment by seansay** [comment]
Thanks again, Steve!

**Comment by seansay** [comment]
I would also try to help on the source code when I had more time  🍻

**Comment by siznax** [comment]
@seansay, can you explain to me why it may be cleaner to do this:

```python
>>> b = wptools.page("Björk").get(timeout=5, proxy="")
>>> c = wptools.page("John Cage").get(timeout=5, proxy="")
>>> z = wptools.page("Frank Zappa").get(timeout=5, proxy="")
```

instead of this?

```python
>>> wptools.set_timeout(5)
>>> wptools.set_proxy("")

>>> b = wptools.page("Björk").get()
>>> c = wptools.page("John Cage").get()
>>> z = wptools.page("Frank Zappa").get()
```

I see that `requests` prefers the former, but it doesn't look as clean to me.

Also, in that case, we would need to add `(timeout=0, proxy='')` arguments to all the `get_` methods?

**Comment by seansay** [comment]
@siznax 
First, it seems that you add `set_timeout` to the `WPTools` class not the module?

One benefit I came up with is that you can dynamiclly decide the timeout and proxy based on the complex rules(without changing the module attrbite):

1. you have many proxies , and you randomly choose one each time.
2. timeout can be related to proxies if you're doing that precisely

it's good to just have one line of code instead of `set_timeout` then `set_proxy` and then `get` in this case

**Comment by siznax** [comment]
Good points @seansay. I'll make it so all API entrypoints support it:

```
get(timeout=<seconds>, proxy=<proxy>)
get_claims(timeout=<seconds>, proxy=<proxy>)
get_imageinfo(timeout=<seconds>, proxy=<proxy>)
get_parse(timeout=<seconds>, proxy=<proxy>)
get_query(timeout=<seconds>, proxy=<proxy>)
get_random(timeout=<seconds>, proxy=<proxy>)
get_rest(timeout=<seconds>, proxy=<proxy>)
get_wikidata(timeout=<seconds>, proxy=<proxy>)
```

**Comment by seansay** [comment]
@siznax 
thanks Steve, that would be great! 🍺
