### ISSUE TITLE
wikidata item classification

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#31]
it's not really about this lib, but it could be better `wptools` could help on this:

I'm using the `claims` attr from wikidata to classify if the page I get is a musician or musicial group.

```
WIKI_DATA_HUMAN = 'Q5'
WIKI_DATA_BAND = 'Q215380'
WIKI_DATA_ROCK_BAND = 'Q5741069'
```

Now I'm using these three attr, if any page has anyone of these three attr in its claims, I think it's a musician. But the wikidata has tons of this `instance of` attrbite ( it' a tree I guess), so is there any a clever way to tell, whether a wikidata item is a subclass of another wikidata?

Thanks in advanced! Steve

**Comment by siznax** [comment]
Sorry @seansay, I don't know of any clever way, other than the relations described [here](https://www.wikidata.org/wiki/Help:Basic_membership_properties); in particular `x subclass of y` where `x` and `y` must both be classes. I would take a look at [**Wikidata:WikiProject_Music**](https://www.wikidata.org/wiki/Wikidata:WikiProject_Music) and try some [SPARQL queries](https://query.wikidata.org). Sorry I can't be more help. I can't even find `instance of (P31) musician (Q639669)`: 

https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ639669.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0ALIMIT%20100

Let me know if you discover some way `wptools` could help via the Wikidata API.

**Comment by seansay** [comment]
@siznax 
Thanks youe help!

After some research I found this `http://wdq.wmflabs.org/`, and a query `http://wdq.wmflabs.org/api?q=tree[2088357][][279]` (P279 is `subclass of`)
will return all subclass of Q2088357(music enseble), this way I can decide whether a wikidata item is a band
