### ISSUE TITLE
props and claims differences

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#36]
Hi Steve,

I'm wondering the page object's `props` and `claims`, what's the difference?
Am I correct props it's more like the raw data, and `claims` it's parsed to be used more friendly in the library?

thanks so much!

**Comment by siznax** [comment]
Thanks for your question @seansay. I decided to explain this in the wiki, which I hadn't used until now. So, you're responsible for yet another improvement!

**Comment by siznax** [comment]
I hope this answered your question @seansay.
