### ISSUE TITLE
Consider custom exception class

### ISSUE THREAD

**Issue by siznax** [siznax/wptools#37]
It would be nice to have a custom exception class if necessary. It could protect users from changes in our implementation (for example, we raise`pycurl.error` now, but that may change to a `requests` exception in the future), but we should have a clear and strong case for making another class.

**Comment by seansay** [comment]
that's a very good point here Steve

**Comment by siznax** [comment]
I'm going to close this. The most common exception I see now is `LookupError`, and it's unlikely we'll move away from pycurl.
