### ISSUE TITLE
Scripts/ not distributed with PyPi

### ISSUE THREAD

**Issue by siznax** [siznax/wptools#4]
Oh, Python Packaging, you hot mess you.

Suggestions welcome.

**Comment by siznax** [comment]
Ah, I see, just add the empty file `scripts/__init__.py` and that directory should get distributed. However, I don't know an easy way to get them on your shell path. Should probably consider making the methods so convenient as to make the scripts unnecessary. Next release...

**Comment by 0x9900** [comment]
__init__.py is not enough to distribute tools/scipts that you want to install.

https://github.com/siznax/wptools/pull/6

**Comment by siznax** [comment]
Fixed with #6
