### ISSUE TITLE
Add support for get_wikidata continuations

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#48]
Hi Steve,
i'm not sure this is possible yet in wikidata's api, but I have this list of id(1000+), I only need to know its title right now.  Instead of query one by one, it would be great to just have its name in one query.

**Comment by siznax** [comment]
Thanks for the question @seansay. The Wikidata API [wbgetentities module](https://www.wikidata.org/w/api.php?action=help&modules=wbgetentities) we use supports getting 50-500 titles:

```
Maximum number of values is 50 (500 for bots).
```

I plan to support continuations on all entrypoints by 1.0.

**Comment by siznax** [comment]
I looked into this a bit more. It shouldn't be too difficult. If we add properties to claims as well in `_marshal_claims()`, then our `get_claims()` query will have both `P` properties and `Q` items:

```
https://www.wikidata.org/w/api.php?action=wbgetentities&formatversion=2&ids=Q14623681|Q14623683|P535|Q6625963|P2387|P434|Q1860|Q159288|Q7979|P1273|P2469|P1375|Q145|P1284|Q214917|Q36180|Q351735|Q7066|P2168|P1415|P1417|P2163|Q25169|P2963|P1263|P998|P1266|Q463035|P1207|P1816|P1015|Q2576795|Q721|P2605|P2604|P213|P1315|P214|Q187655|Q14623678|P1953|Q14623675|Q14623673|P691|P856|P18|P1559|P345|P1006|P349|P1005|P1003|P2611|P2191|Q12152|Q42406|Q3739104|P269|P906|P866|Q6581097|P3106|P646|Q4961791|Q28389|Q4853732|P373|P648|P2626|P1233|P1442|P570|Q1042294|Q6607|Q7758404|P271|Q482980|P2188|Q902712|Q84|P409|P569|Q578895|Q761469|P1258|P2435|P244|Q350|Q533697|P1670|Q691283|P1695|Q5|P2019|P268|Q245068|P396|P950|Q909993|P1477|P1368|Q18844224|Q8935487|Q9531|Q3414212|P227|P949|Q261113|P947&languages=en&props=labels&redirects=yes&sites=&titles=
```

We'll have to limit `&ids=` to 50:

```
{
    "warnings": {
        "wbgetentities": {
            "warnings": "Too many values supplied for parameter 'ids': the limit is 50"
```

That will give us claims like this:

```
claims = {
  u'Q14623681': None,
  u'Q14623683': None,
  u'P535': None,
  u'Q6625963': None,
  u'P2387': None,
...
```

until we set ALL the labels in `_set_claims_data()` instead of only the ones defined by `_WIKIPROPS`:

```
claims = {
  u'P535': u'Find a Grave grave ID',
  u'Q6625963': u'novelist',
  u'P2387': u'Elonet person ID',
  u'P434': u'MusicBrainz artist ID',
  u'Q1860': u'English',
...
```

then give ALL properties and items appropriate labels:

```
props = {
  u'P214': [u'113230702'],
  u'P1477': [u'Douglas No\xebl Adams'], 
  u'P551': [u'Q159288', u'Q84', u'Q909993'],
  u'P735': [u'Q463035', u'Q261113'],
  u'P949': [u'000163846'],
...
```

into the `wikidata` attribute.

**Comment by siznax** [comment]
Not to be confused this with continuations on `get_claims`, which is now #56.

**Comment by siznax** [comment]
See #57
