### ISSUE TITLE
default wikiprops

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#55]
Hi Steve,

When I'm trying to request a ne property of a wikidata item, it's kind of hack in code right now:

` simone._WIKIPROPS['P21'] = 'gender'`

(maybe one should never set private attribute out of class definition?)

Maybe we could set up a method on the module object `wptools` to set up an global props dict, and then provie a optional parameter on the page function ,

`wptools.page(wikibase='Q123', props=['P123', 'P21']).get_wikidata()`, maybe something like this? 
The parameter in the `page` method should override the global config props when presents

just a rough thought, tell me what you think.

🍰

**Comment by siznax** [comment]
Good point about the private attribute. We should have a accessor method.

We would need to provide labels with the props too, so maybe like this?

```
wptools.page(wikibase='Q123', props={'P123': '<label>', 'P21': '<label>'})
```

**Comment by siznax** [comment]
Ideally, we would get all labels for all `P` (properties) and `Q` (items) and not worry about supplying labels, but that will require support for continuing queries (#48), and I plan to do that before 1.0.

**Comment by siznax** [comment]
@seansay, I added support for this with bac9ed0cf3ce1eaa552fcbff107eba9e7289c5eb

**Comment by siznax** [comment]
Does this seem like a reasonable solution @seansay?

**Comment by siznax** [comment]
I'll close this for now. Please re-open to continue the discussion! 😎
