### ISSUE TITLE
Categories get

### ISSUE THREAD

**Issue by andresbravog** [siznax/wptools#89]
There is a wiki page explaining how to get a specific category entity and its members: https://github.com/siznax/wptools/wiki/Categories

But when trying I do get:

```
>>> import wptools
>>> cat = wptools.cat('Category:Book censorship')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'cat'
```

And checking the code there is no method such as `cat` neither `category`.

How can I get this functionality working?

Thanks in advance

**Comment by andresbravog** [comment]
nevermind if someone is dealing with this the correct usage is:

```
import wptools
cat = wptools.category('Category:Book censorship')
cat.get_members()
```

**Comment by siznax** [comment]
Thanks for pointing this out, @andresbravog. I've updated the wiki. Category usage is ostensibly described here: https://github.com/siznax/wptools/wiki/Usage#category-usage. The "Knowledge base" page is where we keep notes about how we've done things and may not always be correct.
